{% set name = "codecov" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf30a41f65e747b159e2a749d1f9c92042d358bba0905fd94d3def3a368e592c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - codecov=codecov:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - coverage
    - requests >=2.7.9

test:
  imports:
    - codecov
  commands:
    - codecov -h
    - pip check
  requires:
    - pip

about:
  home: https://github.com/codecov/codecov-python
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Hosted coverage reports for Github, Bitbucket and Gitlab
  doc_url: https://github.com/codecov/codecov-python
  dev_url: https://github.com/codecov/codecov-python

extra:
  recipe-maintainers:
    - CJ-Wright
    - marcelotrevisani
