{% set name = "codecov" %}
{% set version = "2.0.15" %}
{% set sha256 = "474700e009b4175a3614cf8678a25d591e66cea2af2c1bbe80b53faec10621f3" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # Not on pypi (at time of packaging)
  url: https://github.com/codecov/codecov-python/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - coverage
    - requests >=2.7.9

test:
  imports:
    - codecov
  commands:
    - codecov -h

about:
  home: https://github.com/codecov/codecov-python
  license: Apache-2.0
  license_family: Apache
  summary: 'Hosted coverage reports for Github, Bitbucket and Gitlab'
  doc_url: https://github.com/codecov/codecov-python
  dev_url: https://github.com/codecov/codecov-python

extra:
  recipe-maintainers:
    - CJ-Wright
