travis:
  secure:
    BINSTAR_TOKEN: HOghRrB4knsYawF7jqhRrUUs2yxyPOdMC3akHnrhTvkVdpKJlEWZG4SuZQKK3wzpgeSSSgQszx3yQeTB/QI3Hl4Lm3BqBrqHIh0MzdmHSI1XF++3L4ajmsnZg4Aaa94/itRTpTPMPq5kBiNc+Z2SCmdBoSzwi0o+czzrD+mo+SraS0GGHumBEak1IvoQhhykxx+Lmu+wivN9/ujMcA+veCSXN6NbdWcSgbi8sXncyvVuwzXwg1uO49QiwpYmqjUq0t/aMsOdtnmhY1MIk5X+GsSUggD0GrTSAJtIy3HzLVzr4LVhW2sj8XwFpIxskLWV5LYKwyoGFV/9Ueczvqh5ERpyhFa3mX3SazCZJbVNDE43hPtovIyOf1JYTySlRYEqQijAwVNPKRYSsyOTbJqyQRl2tbYxFMi0CDYvMBJ3J+vFGRxOxjNzXznw0v9tywTt95ftjaybfUxem7DwUPOYyV0DVUdP9v6JYw3GLOVjj7LgVVdC8OPFhgC9xgSn6gSbm+7NNla/kwclN0XDahEXsQCscXscFQ3frA4ZnBxbl+4tMzVe/0dt4WmYyU/AoQQxSx+Vm27/McF0p9Jw4Oe2l8oLM7CmKyZtkd2x7G6lxVsRWdvR+rpDD2ZcYtdSSAfx3cqN6zE7yfPK47w/xbc9c/ksZU1XR05wdP/4rILloUg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
