travis:
  secure:
    BINSTAR_TOKEN: Ko4F8zhPBcbHWdm1ZWmN2SGVRyAUsOessHKWCRG8YRWjCE+I5bwBlICJs4A2j97BnTSijKBFu6AdOuX+PE+OfYkW3sLVyHHV+YvwNvSmYwlQWN+9tnGPhCfN0LCW9iPdDc8Ktsdj349GvOfuvFZIjfCKxRsiQbwSljdL1d/Hc5T/YarW+nJAoSJeTowS51DFlCl9KAh2MznmXw1/4ZvVKcyqkEqtWKAxUKsN1EgwheaJCXo/d361EVt7B5NzH6aUQPNE73fujVrhSHWpEEJ12Iqfu/CIf4amCf/nyj33unIfwPkoHErnBOJ/hlMiqQMepaWD9eiQSCmU/psGPoDoOi/yZobsCalE5NLy54X89BRWDzF+0/RmUm7UIoYg+m6VN08HLRcg7voxEJg0FNt3ghguIfndySATqbjYsKbC3hKcW3P9o+rNhhDrxLSbRRprYY4q3rHxjJIMBPR7y3v3PMMjsC+f9MDzf0XpfRtLJvjAO/W27a5UUox4vXF/2+PrNlKpUEyzKEjfBg5ux2Q45XCBd7NWPoyxwAVG2/ogdjG5PD1aAXMr/5cbrOFLWgXua+YlpwT+omc+iiEKXyIg4VevmzJFyIZiz83tDXXDqwoZNShx2Pcg9cI11Y6cAs+gN5qSt/WUhzA7/CXfAnKOoYTEpREjR9MaHBjQ/VIOcm8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
