travis:
  secure:
    BINSTAR_TOKEN: i5cfkfau4DdN777PsZw7izUiJvkbEe/jqAwIiBz/c56dOc+NvmT7ch3/8Yd/7efOS6E1V75qapTho5uAvZP+tVlEDlGj2GjepA1EAHWrWdYM1DNaIJnx+yzYRZpv0NrA1bGSdVhWRxDc78vqaLkh+X6FG0JFguJTh3jssE9RTw9O13CrFklTqSMekqghs/ByRqjQnjhXmxcIgLXgifP+TKZ/kcyWlbRBJInJqg4N5zYFqSnX0vIspZ91kDFajypM5DQUIv5lwko9hSW9lpJxwoEpHLb4BuycOdsneLGwNp4GyIsjbI00olr9+PkjjiQOQjUb7L3bIXJ8tVO4Jw+YjueNzTTOktXZE7/R3eMFe/ZSSd2B2wx+dPWguIVAflmSApV09UJr2HZiR1TkJa6GM0XDbdNo3Dw6+ixDvMsfjO2XRqjFri9KU64XgwqYWCW66gZqE8BygKXkz9QuMlAq90Z6WiWkNAm7r6kiq2Sgc89G9STMUdkq4PRI9kax9gvm6LJCkulh4owiX/m74XTobNHa+iOtdb/w8NNhQKhMG1pSYJkx3wIfGQA0tfrPwry3ZbHVoG4lyCA6/fZYOgvxk7ruySSDXSWI1BPGkllXh4P7XrcBNGEEsjnsUw3GColMo3trKQQ1NjFj+SZNX1xvOAEP79cCu4kObzXchxt/BaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
